version: "3"

services:
  app:
    container_name: gh-rankings-server
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - APP_ENV=docker
    depends_on:
      - mongo
    ports:
      - "${APP_PORT}:80"
    networks:
      - backend
    volumes:
      - ./docker.env:/app/docker.env
      - ./storage:/app/storage

  mongo:
    image: mongo:latest
    container_name: gh-rankings-mongo
    restart: always
    networks:
      - backend
    volumes:
      - mongo:/data/db

networks:
  backend:

volumes:
  mongo:
